### ISSUE TITLE
Spec classes aren't marshallable

### ISSUE THREAD

**Issue by barrettkingram** [seattlerb/minitest#794] opened 2019-06-10 15:11 UTC
Spec classes can't be marshal dumped. This prevents Rails 6 parallel testing from being used with minitest specs.

Reproduced with ruby-2.6.3:
```ruby
gem "minitest"
require "minitest/autorun"

class Meme
  def i_can_has_cheezburger?
    "OHAI!"
  end
end

describe Meme do
  before do
    @meme = Meme.new
  end

  describe "when asked about cheeseburgers" do
    it "must respond positively" do
      @meme.i_can_has_cheezburger?.must_equal "OHAI!"
    end
  end
end

class TestMeme < MiniTest::Test
  def setup
    @meme = Meme.new
  end

  def test_that_kitty_can_eat
    assert_equal "OHAI!", @meme.i_can_has_cheezburger?
  end
end

spec, test = Minitest::Runnable.runnables.reject { |s| s.runnable_methods.empty? }

# This works fine
remote_test = Marshal.load(Marshal.dump(test))

# This fails with something like:
# test.rb:39:in `dump': can't dump anonymous class #<Class:0x0000561978b2c2e8> (TypeError)
remote_spec = Marshal.load(Marshal.dump(spec))
```

**Comment by blowmage** [comment] 2019-06-10 17:25
There is a fix for this in blowmage/minitest-rails#218

**Comment by zenspider** [comment] 2019-06-11 09:33
This looks like a duplicate of #716 ?

**Comment by barrettkingram** [comment] 2019-06-11 13:41
I did come across that PR while searching for solutions to this issue (probably should have mentioned that in the issue description). However it looks like your patch linked in the gist only fixed marshalling for the `Minitest::Result`, not the spec class itself.

**Comment by zenspider** [comment] 2019-08-24 21:39
Right... but my patch decouples the results from the classes entirely. So this isn't for sending results over the wire? Why do you need to marshal the spec class?

**Comment by zenspider** [comment] 2019-08-30 22:39
Poke... @blowmage as well.

**Comment by barrettkingram** [comment] 2019-10-31 21:26
The way I understand it, with Rails 6 parallel testing, the parent process [collects all of the test classes/methods in a queue and serializes each one](https://github.com/rails/rails/blob/v6.0.0/activesupport/lib/active_support/testing/parallelization.rb#L25-L28). Then the child processes [pull jobs from that queue (over DRB), run the test, and pass the result back](https://github.com/rails/rails/blob/v6.0.0/activesupport/lib/active_support/testing/parallelization.rb#L73-L107).

**Comment by zenspider** [comment] 2021-12-14 04:24
I've got this working with a slightly different solution. Sorry it took me so long.

**Closed by zenspider** 2021-12-14 04:24 UTC
