### ISSUE TITLE
gem install on nfs

### ISSUE THREAD

**Issue by optimum-dulopin** [seattlerb/minitest#435] opened 2014-05-31 00:04 UTC
Hi,

i tried to install minitest with rbenv, but it always failed

ERROR: While executing gem ... (Errno::EACCES)
Permission denied @ rb_sysopen - /nfs/http8/user_xxxx/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/minitest-5.3.4/.autotest

I tried with all older version > 2.12.1

ruby 2.1.2
os : ubuntu 12.07 LTS

thanks

**Comment by southerngs** [comment] 2015-01-13 21:12
I've also have the same problem using chruby.  As @cbay noted the root cause is related to NFS.  After I changed my configuration to install gems in an alternate directory the problem was fixed.  Also I think it would make sense to either have this as an open issue, or add a note to the README that installs to NFS mounted partitions are not supported.

**Comment by EHadoux** [comment] 2015-01-16 16:56
Actually, as minitest seems to be required to install new versions of Ruby (at least with rbenv), it prevents me from installing Ruby 2.2.0.
Do you know a workaround for this? Because, installing minitest in local will not solve the problem, the installer will try to install it anyway.
I don't think I can change the installation directory either (again, using rbenv).
And I also am on a NFS drive.

**Comment by zenspider** [comment] 2015-01-17 11:20
> Really ?

@breinz, yes, really. Your "minimal" steps essentially start with "create an account on X, give them all your personal information, sign up your email for registration (and spam!), all in a language you don't read or speak well"... I start to think that perhaps it isn't actually all that minimal. All of this for a bug that has < 10 people saying it is an issue for them against a current release that has 186K installs already. Can you see why I might not want to deal with your "minimal" steps?

> For a response I need the minimal steps which I can run to see if it helps. As you can see, here I have no steps ... and I never dealt with NFS.

I'm obviously not understanding this statement. "Permission denied @ rb_sysopen - **/nfs**/http6/breinz/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/minitest-5.5.0/.autotest"

> Sorry to be sarcastic, but it took me a lot of patience to provide you a straightforward repro, so your answer is a bit disappointing.

When your apology for being sarcastic is dripping with the sarcasm above it, the apology seems to get a bit drowned out.

**Comment by zenspider** [comment] 2015-01-17 11:22
@EHadoux or @cbay can either of you test for me whether installing minitest with `sudo` works? IE, is it _just_ a perms issue or is it something worse in NFS?

**Comment by EHadoux** [comment] 2015-01-17 11:44
I am sorry, as far as I am concerned I cannot do that, I have no root access on this machine and I have no NFS where I can have root access. 
But actually, your gem __hoe__ seems to suffer from the same desease.

**Comment by zenspider** [comment] 2015-01-17 13:04
No worries. I figured that might be the case. Maybe @cbay

**Comment by EHadoux** [comment] 2015-01-19 13:17
I tried with __hoe__ and the problem is the same.
However, the problem is not always on the same file: 
```gem install hoe```
```
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /home/hadouxe/.gems/gems/hoe-3.13.0/.autotest
```
or
```
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /home/hadouxe/.gems/gems/hoe-3.13.0/Hoe.pdf
```
or
```
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /home/hadouxe/.gems/gems/hoe-3.13.0/.autotest
```
I know that in the doc it is specified to use ```sudo``` but rbenv does not.
As a first thought, what I see as being common to either minitest and hoe and different from all other gems is the lack of a gemspec file.
Obviously, for a reason I ignore, it needs to open the files to install the gem and the rights do not seem to be properly set (yet?).
Last point, cloning, executing rake and then gem install __the pkg__ (i.e., the local gem built at the previous step) works.
However, we cannot do that directly for minitest as it will try to install hoe from the net. We need to install hoe this way __then__ minitest also this way.

**Comment by coorasse** [comment] 2015-02-04 22:25
why is this issue still open? do you need more informations? All steps to reproduce the error  by @breinz  are clear I think.

**Comment by zenspider** [comment] 2015-02-05 00:49
@coorasse I think I was pretty clear above.

**Comment by coorasse** [comment] 2015-02-05 08:54
We offered to provide you credentials and all the previous steps already done until the error. @breinz  did it and the same did I months ago. You would have only to connect through ssh and execute `gem install`. 

Would that minimal enough to take a look and try to resolve the issue?

If your answer is positive I'll provide you a username and a password into a vps with nfs where you can reproduce the error.

**Comment by EHadoux** [comment] 2015-02-05 09:09
FYI, this issue, as the changement of name stated, does not seem to be related to rbenv (everybody seemed to have rbenv install in the tests above).
I tried to install from source on the nfs and it failed again on minitest.
Is there any ways to bypass minitest installation?

**Comment by coorasse** [comment] 2015-02-05 09:26
@EHadoux  you can recompile it by yourself and place it in bundler cache folder: http://forum.alwaysdata.com/viewtopic.php?pid=18082#p18082

Is just a workaround waiting for the issue to be fixed but at least you are able to proceed.

**Comment by EHadoux** [comment] 2015-02-05 09:34
@coorasse Yes, thank you. I was think more about a configuration stuff like a flag or whatever.

**Comment by zenspider** [comment] 2015-02-07 01:32
@coorasse / @breinz :

I was hoping that @cbay would get back to me with info since he's an admin on the server in question. Since he hasn't, then yes, a login seems necessary to get to the bottom of this.

**Comment by coorasse** [comment] 2015-02-07 09:47
Here you are! New steps:
# login with credentials I sent to you by email
# run `gem install minitest`

**Comment by zenspider** [comment] 2015-02-07 13:49
This is a bug in rubygems and is now fixed. Unfortunately, because rubygems is bundled with ruby itself (instead of ruby downloading it or at least self-updating before installing the other gems), it isn't going to be fixed realistically until a new version of ruby is released with this patch. I would hope to see it in ruby 2.2.1 (or maybe 2.2.0.pX+1)

/cc @drbrain

**Comment by EHadoux** [comment] 2015-02-07 17:44
Thank you very much for this and sorry for all the drama.

**Comment by mislav** [comment] 2015-05-29 01:08
Hi @zenspider do you have a link to the RubyGems bug? I've just checked my Ruby versions 2.1.2 up to 2.2.0 and it seems all of them have minitest (that ships with Ruby) installed as read-only files. Repro steps:

1. Install Ruby 2.2.2 to `/path/to/2.2.2`
2. `find /path/to/2.2.2 ! -perm -u+w` to find files you don't have write access to
3. The output lists a bunch of files from `lib/ruby/gems/2.2.0/gems/minitest-5.4.3/`

I'm just curious what step of Ruby installation made these files read-only and whether it's by design.

**Comment by zenspider** [comment] 2015-05-29 01:17
The files are read-only on packaging as a result of my development process... the bug in rubygems is that they open a file specifying the perms and then try to write to it. On most file systems, that seems to be OK, but on (certain versions of?) NFS, it blows up.

Looks like the fix shipped in rubygems v 2.4.6 on 2015-02-05.

**Comment by mislav** [comment] 2015-05-29 01:26
@zenspider Thanks! It's not blowing up for me during Ruby installation; I was just wondering why the permission discrepancy.

**Comment by zenspider** [comment] 2015-05-29 01:41
Just how I do things in my VC.

**Comment by zenspider** [comment] 2015-05-29 01:42
Oops. I didn't see that I didn't close this ticket when I should have.

**Closed by zenspider** 2015-05-29 01:42 UTC
