### ISSUE TITLE
Error running tests: "MySQL client is not connected: BEGIN"

### ISSUE THREAD

**Issue by alxx** [seattlerb/minitest#744] opened 2018-02-10 14:03 UTC
Hi,

I'm using minitest 5.11.3 with Rails 5.1.4 (OSX 10.13.3, MySQL 5.7.10, ruby 2.4.1) and I get the error above erratically, at random points during the test run, either during unit tests or controller tests (I don't have any other tests for now).

When it happens, it's usually accompanied by an exception in test_unit/reporter.rb, like, for example:

```
$ rails test test/controllers/mobiles_controller_test.rb
Running via Spring preloader in process 17799
Run options: --seed 8245

# Running:

.......E

Error:
MobilesControllerTest#test_wrong_signature:
ActiveRecord::StatementInvalid: Mysql2::Error: MySQL client is not connected: BEGIN
    


/Users/alxx/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/test_unit/reporter.rb:70:in `method': undefined method `test_wrong_signature' for class `Minitest::Result' (NameError)
```

Running the same command line might cause the same error to appear at a totally different test, or not at all.

This only happens in test mode. In development mode everything works fine.

My Gemfile:

```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.4'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'unicorn'
gem 'graphql', ">= 1.7.2"
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end
group :test do
  gem 'minitest', '5.11.3'
end
group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'annotate'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```
I tried to fiddle with a MySQL parameter (namely, I've increased max_allowed_packet) and I thought I saw some improvement, but today I've been seeing the error more often than not.

Any idea how I can go about finding the culprit?

**Comment by zenspider** [comment] 2018-02-24 01:02
The last line of your error hints at #730. But that has nothing to do with the mysql issues you’re having. But your mysql issues have nothing to do with minitest.

So, start by rolling back and pinning minitest (or rolling forward and using edge rails). Diagnose from there.

**Comment by zenspider** [comment] 2018-03-07 09:49
anything?

**Comment by alxx** [comment] 2018-03-07 09:55
Sorry, no. I don't have the time to create a separate project in which to pin minitest or play with other Rails versions. I was hoping this would make more sense to somebody who knows how to fix it.

I realise that the mysql interface (via the mysql2 gem and the client libraries) has nothing to do with minitest, but this only happens with minitest, which is why I posted the issue here.

That's why I hoped that, being perhaps a Rails issue, other people have bumped into it before.

**Comment by zenspider** [comment] 2018-03-07 10:01
Well. The last line of the error is due to a mismatch between rails 5.1 and minitest 5.11. Pin minitest back to 5.10.3 and it should address that part. Then maybe you can dig further into the mysql issue.

I'm considering this a dupe of #730 and closing this until the mysql stuff can be isolated. Please open a new issue with a repro if you can.

**Closed by zenspider** 2018-03-07 10:01 UTC

**Comment by alexanderadam** [comment] 2019-01-09 11:00
Hej @alxx , did you find the source / a solution for the issue?

**Comment by alxx** [comment] 2019-01-09 11:09
Hi @alexanderadam. No, I didn't find either the source or the solution. I honestly don't think it's related to the gem, since it only appears with minitest and only in test mode. I just stopped using minitest altogether.

**Comment by ConfusedVorlon** [comment] 2019-01-10 13:51
fwiw - I'm getting this error using rspec. Minitest isn't even in my gemfile.

relevant gems
```
gem 'rails', '~> 5.2.0'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'rspec-rails', '~> 3.8'
```

**Comment by tramuntanal** [comment] 2019-06-11 16:59
Hi there,
We're also having this error in our test suite.
I've been able to reproduce what seemed a random error predictably. My current use case is an `ActionController::TestCase` test (I'm on minitest (5.11.3)) that executes an ActiveJob, then during the Job I get the following backtrace:

```ruby
...
[ActiveJob] [SendPushNotificationsJob] [d7c91bbf-7993-480c-b4ff-8a1db43daade]   [1m[36mApp Load (1.0ms)[0m  [1m[34mSELECT  `apps`.`id`, `apps`.`name`, `apps`.`description`, `apps`.`icon_file_name`, `apps`.`icon_content_type`, `apps`.`icon_file_size`, `apps`.`icon_updated_at`, `apps`.`multievent`, `apps`.`active`, `apps`.`created_at`, `apps`.`updated_at`, `apps`.`multievent_screen_img_file_name`, `apps`.`multievent_screen_img_content_type`, `apps`.`multievent_screen_img_file_size`, `apps`.`multievent_screen_img_updated_at`, `apps`.`bg_color`, `apps`.`default_locale`, `apps`.`min_version_android`, `apps`.`min_version_ios`, `apps`.`firebase_analitics_url`, `apps`.`notification_config_key`, `apps`.`max_programs`, `apps`.`requires_login` FROM `apps` WHERE `apps`.`id` = 1 LIMIT 1[0m
  [1m[36mNotification Load (2.1ms)[0m  [1m[34mSELECT  `notifications`.`id`, `notifications`.`created_at`, `notifications`.`updated_at`, `notifications`.`event_id`, `notifications`.`platform`, `notifications`.`target_push_id`, `notifications`.`send_to`, `notifications`.`push_notification_platform_msg_id`, `notifications`.`sent_at`, `notifications`.`programmed_send_at`, `notifications`.`notification_type`, `notifications`.`source`, `notifications`.`extras_json` FROM `notifications` ORDER BY `notifications`.`created_at` ASC LIMIT 1[0m
[ActiveJob] [SendPushNotificationsJob] [d7c91bbf-7993-480c-b4ff-8a1db43daade]   [1m[36mSegmentationLabel Load (0.7ms)[0m  [1m[34mSELECT `segmentation_labels`.* FROM `segmentation_labels` INNER JOIN `notifications_segmentation_labels` ON `segmentation_labels`.`id` = `notifications_segmentation_labels`.`segmentation_label_id` WHERE `notifications_segmentation_labels`.`notification_id` = 107[0m
[ActiveJob] [SendPushNotificationsJob] [d7c91bbf-7993-480c-b4ff-8a1db43daade] NotifService::DummyNotifService.send_push_message(#<NormalPushNotification:0x000055a61aac2c48>)
  [1m[35m (1.4ms)[0m  [1m[31mROLLBACK[0m
[ActiveJob] [SendPushNotificationsJob] [d7c91bbf-7993-480c-b4ff-8a1db43daade]   [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
[ActiveJob] [SendPushNotificationsJob] [d7c91bbf-7993-480c-b4ff-8a1db43daade] ### Couldn't finish SendPushNotificationsJob.perform due to: <<Mysql2::Error::ConnectionError: Lost connection to MySQL server during query: BEGIN>> /home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:200:in `begin_db_transaction'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:175:in `initialize'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `new'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `block in begin_transaction'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:197:in `begin_transaction'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:238:in `block in within_new_transaction'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:424:in `update'
/home/oliver/prog/coditramuntana/suitevent/suitevent/app/domain/notif_service.rb:32:in `send_push_message'
/home/oliver/prog/coditramuntana/suitevent/suitevent/app/domain/notif_service.rb:61:in `send_push_message'
/home/oliver/prog/coditramuntana/suitevent/suitevent/app/jobs/send_push_notifications_job.rb:21:in `perform'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/execution.rb:39:in `block in perform_now'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/logging.rb:46:in `block in tag_logger'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/logging.rb:46:in `tag_logger'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/execution.rb:38:in `perform_now'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/execution.rb:24:in `block in execute'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:73:in `block in wrap'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/execution.rb:22:in `execute'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activejob-5.2.2/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/oliver/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
[ActiveJob] [SendPushNotificationsJob] [d7c91bbf-7993-480c-b4ff-8a1db43daade] Performed SendPushNotificationsJob (Job ID: d7c91bbf-7993-480c-b4ff-8a1db43daade) from Async(default) in 11.23ms
```

Then what is weird is that minitest says that the following test failed due to:
`ActiveRecord::StatementInvalid: Mysql2::Error: MySQL client is not connected: BEGIN`.
In the log/test.log file I can't even see the second test is starting.

Being an illiterate in Minitest and Rails connection pool can't determine if I have to forward this to another gem or keep it here.
Should this issue be reopened now that we have more clues?

**Comment by jameshibbard** [comment] 2019-07-30 14:17
Same thing happening here.

ruby 2.5.1
mysql2 (0.5.1)
minitest (5.11.3)
rails (5.2.3)

**Comment by jronallo** [comment] 2019-12-01 16:07
I had intermittent issues with tests and ActiveJob and setting the queue_adapter to :inline seems to have resolved them. Otherwise jobs were still running after ROLLBACK which stalled tests completely.
