### ISSUE TITLE
Skipping a test can fail in a non-obvious way

### ISSUE THREAD

**Issue by bfoz** [seattlerb/minitest#317] opened 2013-06-21 22:22 UTC
The current skip implementation doesn't completely prevent a spec from running. For example, the following expectation will cause a failure, rather than a skip:

```ruby
it "failing test" do
    1.must_equal 2
    skip
end
```

Granted, this may be an edge case, but there's nothing about the skip command that would lead a user to realize that it must be the first line of the block. It's a non-obvious failure mode and can be a little astonishing for the user. At least, it was for me.

**Comment by zenspider** [comment] 2015-01-21 00:40
This code is working as intended. There is already an open ticket on skip/focus so I'm closing this one.

**Closed by zenspider** 2015-01-21 00:40 UTC
