### ISSUE TITLE
assert_match should only increment assertions by 1 (not 2)

### ISSUE THREAD

**Issue by odigity** [seattlerb/minitest#584] opened 2015-10-07 15:10 UTC
I just noticed that when I use assert_match, it increments assertions by 2.  I looked in the code to see why, and found the method definition here:

https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L223

    def assert_match matcher, obj, msg = nil
      msg = message(msg) { "Expected #{mu_pp matcher} to match #{mu_pp obj}" }
      assert_respond_to matcher, :"=~"
      matcher = Regexp.new Regexp.escape matcher if String === matcher
      assert matcher =~ obj, msg
    end

I'm new to minitest, so I may have some missing context, but wouldn't it better to use something *other* than an assert* method to ensure the matcher passed in responds to `=~`?  The point of that code is to validate inputs to the assertion, whereas the point of an assertion is to test the behavior of the app code the test suite is being applied to.

Can't this line be replaced with some kind of error checking that isn't based on calling an assert* method, thereby incrementing the counter and confusing the dev writing tests?

**Comment by zenspider** [comment] 2015-10-14 00:07
Short version: no. 

Longer version: Define "better". Having an assertion use another assertion provides more targeted error messages and reuses code maximally. What do you care what the assertion count is as long as it gets the job done? Are you really counting the number of `assert` lines and comparing against the reported number? Why? What happens when you refactor your tests?

This is a dupe of at least one other issue (that I also rejected). Closing.

**Closed by zenspider** 2015-10-14 00:07 UTC
