### ISSUE TITLE
Minitest::UnexpectedError when a fixture exists named "yes" or "no"

### ISSUE THREAD

**Issue by GeorgeDewar** [seattlerb/minitest#536] opened 2015-04-29 05:43 UTC
I've noticed a hard-to-nail-down problem.

If I have a fixture named "yes" or "no", such as:

```
yes:
  text: Yes
```

... then upon running any test, I receive the following unhelpful error:

```Minitest::UnexpectedError: TypeError: no implicit conversion of true into String```

There is no other output that helps narrow down the problem. 

I now realise that this is really a YAMLism, but perhaps Minitest could indicate that a fixture named ```true``` is not allowed?

**Comment by zenspider** [comment] 2015-04-29 07:25
I don't think this really has anything to do with minitest.

**Comment by zenspider** [comment] 2015-04-29 07:26
> There is no other output that helps narrow down the problem.

What do you mean by that?

**Comment by teoljungberg** [comment] 2015-04-29 08:14
@GeorgeDewar There is a list of reserved words in the YAML spec which you are not supposed to use - http://yaml.org/type/bool.html `yes` and `no` is in that list. If you really need to use them, wrap them inside quotes

**Comment by teoljungberg** [comment] 2015-04-29 08:14
So it's not a minitest-problem, but a YAML problem

**Comment by GeorgeDewar** [comment] 2015-04-29 21:27
Sorry guys, I had written most of that before realising that it was a YAML problem which probably caused confusion, but then decided to submit it anyway because of the below:

> What do you mean by that?

@zenspider I may be missing something as I don't have much experience with Rails testing, but my concern was really more with the lack of a detailed error message that arises from a problem loading the fixtures. I have subsequently found that if I attempt to load the fixtures into the database outside of minitest (```rake db:fixtures:load RAILS_ENV=test```) then I get a proper backtrace.

```
TypeError: no implicit conversion of true into String
/home/georged/.rvm/gems/ruby-2.2.2@submissions/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:636:in `gsub'
/home/georged/.rvm/gems/ruby-2.2.2@submissions/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:636:in `block (2 levels) in table_rows'
...etc
```

**Comment by zenspider** [comment] 2015-04-30 09:58
Sorry, you're not providing enough information for me to act on this. I can't reproduce an error, so I can't fix anything. Loading the yaml above is fine. Calling gsub on it is also fine. I've tried several variants on this _including_ simply raising TypeError and always get a backtrace:

```ruby
require "yaml"
require "minitest/autorun"

class YamlLoader
  def load path
    # YAML.load_file path
    # true.gsub(//, '')
    raise TypeError, "no"
  end
end

class BadYaml < Minitest::Test
  def test_bad_yaml
    hash = YamlLoader.new.load("bug02.yaml")

    # hash.each do |_, row|
    #   row.each do |key, value|
    #     row[key] = value.gsub("$LABEL", label) if value.is_a?(String)
    #   end
    # end

    flunk "not yet"
  end
end
```

gives:

```
  1) Error:
BadYaml#test_bad_yaml:
TypeError: no
    bug02.rb:9:in `load'
    bug02.rb:15:in `test_bad_yaml'
```

Without more info, I'm afraid I won't be of much help.

**Comment by zenspider** [comment] 2015-05-08 23:54
Anything?

**Comment by zenspider** [comment] 2015-05-27 21:40
Closing.

**Closed by zenspider** 2015-05-27 21:40 UTC
