### ISSUE TITLE
Stub does not work with BasicObject [decorators]

### ISSUE THREAD

**Issue by molfar** [seattlerb/minitest#776] opened 2018-09-24 07:35 UTC
Stubbing do not work with decorated by SimpleDelegator objects:

```
test "decorators" do
  class Singer < SimpleDelegator
    def sing
      "singing"
    end
  end

  class Human
  end

  singer = Singer.new Human.new
  singer.stub :sing, "khe" do
    assert_equal "khe", singer.sing
  end
end
```

Expected test pass, but get error (not failure):

```
Error:
WarehouseReservationTest#test_decorators:
NameError: undefined method `sing' for class `#<Class:#<WarehouseReservationTest::Human:0x00007faa7cdb8d18>>'
    test/services/warehouse_reservation_test.rb:16:in `block in <class:WarehouseReservationTest>'
```

**Comment by molfar** [comment] 2018-09-24 08:08
I think that's because SimpleDelegator is descendant from BasicObject, bypassing Object. And Minitest::Mock defines stub method for Object class, so instances of SimpleDelegator does not have stub method defined, and they are proxied to decorated object, in this case Human. Which in turn has no sing method, and as result - can not stub it.

**Comment by zenspider** [comment] 2018-09-24 20:00
Yeah. I think you're right on your assessment. You can see that if you add this to your test:

```ruby
    p singer.method(:stub).source_location # => nil
```

In this case, I'd suggest not bothering with stub. It isn't needed in this case:

```ruby
    singer = Singer.new Human.new
    def singer.sing
      "khe"
    end

    assert_equal "khe", singer.sing
```

**Comment by blowmage** [comment] 2018-09-24 20:19
What about moving the stub to the non-delegator object?

```ruby
human = Human.new
singer = Singer.new human
human.stub :sing, "khe" do
  assert_equal "khe", singer.sing
end
```

**Comment by molfar** [comment] 2018-09-25 05:55
@zenspider defining a singleton method works. But it significantly reduces readability, and may change subject state globally, between different tests. Stub method is ideal for such cases, and why not move it higher to BasicObject? If there was no specific cause you originally placed it lower into Object.

@blowmage your code looks the same as mine, and will not work in reason I described above.

**Comment by zenspider** [comment] 2018-09-25 07:08
Well... the ORIGINAL reason I chose Object was because there was no BasicObject at the time. I still haven't officially dropped 1.8 support (tho, in reality, I have). There's probably some nice defensive way to use both that works. .. .actually, no. i can't think of one right now.

Also. It *looks* like not all the methods I need are there:

```rdoc
= Instance methods:

  !, !=, ==, __id__, __send__, equal?, instance_eval, instance_exec,
  method_missing, singleton_method_added, singleton_method_removed,
  singleton_method_undefined
```

**Comment by zenspider** [comment] 2021-02-15 19:42
I'm going to close this one as "works as intended" since BasicObject doesn't provide functionality needed to do the job.

**Closed by zenspider** 2021-02-15 19:42 UTC
