### ISSUE TITLE
`it` block without `do...end` produces inscrutable error message

### ISSUE THREAD

**Issue by droberts-ada** [seattlerb/minitest#749] opened 2018-03-06 00:29 UTC
Consider the following code and tests:

```ruby
# hello.rb
def say_hello
  return 'hello'
end
```

```ruby
# hello_spec.rb
require 'minitest'
require 'minitest/autorun'

require_relative 'hello'

describe 'hello' do
  it 'fails without a do'
    say_hello.must_equal 'hello'
end
```

This code has an error: whoever wrote it forgot to put a `do...end` pair around their test block. 

When this code is run, ruby / minitest produces the following output:

```
$ ruby hello_spec.rb
Traceback (most recent call last):
	5: from hello_spec.rb:6:in `<main>'
	4: from /Users/droberts/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest/spec.rb:83:in `describe'
	3: from /Users/droberts/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest/spec.rb:83:in `class_eval'
	2: from hello_spec.rb:8:in `block in <main>'
	1: from /Users/droberts/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest/spec.rb:11:in `must_equal'
/Users/droberts/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest/spec.rb:23:in `must_equal': undefined method `assert_equal' for nil:NilClass (NoMethodError)
```

This error is not particularly helpful - it doesn't give any sort of context about what went wrong, or how to fix the problem. The only way to discover what went wrong is to have some sort of brainwave, or access to someone who's seen the problem before. This is especially difficult because this sort of mechanical error is more likely to be made by a novice, who is less likely to have the pattern matching skills needed to spontaneously spot a missing `do...end` pair.

Would it be possible to detect this sort of error, and give a more friendly warning or message?

For context, I am an instructor at a bootcamp where we teach TDD in Ruby (and eventually Rails), and I've probably debugged this particular problem about a dozen times in the last week. It's really difficult for novices to figure out what went wrong!

-----

Environment information:

```
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin15]
$ gem list | grep minitest
minitest (5.10.3)
```

**Comment by zenspider** [comment] 2018-03-06 11:22
> Would it be possible to detect this sort of error, and give a more friendly warning or message?

One possibility is a beginner's form of `it` that warns if there is no block passed. That can’t be the default tho, as people expect to be able to outline their pending tests. It feels like a band-aid regardless.

I don’t suppose you would, as an instructor, take this as a hint that the whole “spec style” experiment has failed pedagogically? 😱 What they’ve done is _essentially_ a tricky not-quite syntax error, so ruby tries to run it. It fails not with a syntax error (expecting `end`) but a failure of missing context (running an expectation outside of a test fails to bridge to assertions).

Had they been taught testing with simple classes and methods then they would be missing the `end` to the `def`. Much simpler error and supported by ruby straight up. To me, the problem is opening with SUCH complex forms without the understanding of what’s going on (blocks, metaprogramming, etc) such that they don’t even understand what the `do`/`end` is there for yet. Going with plain classes and methods means you only need to teach _testing_ concepts and not the whole DSL mess on top of it.

**Comment by zenspider** [comment] 2018-03-06 11:27
Compare:

```ruby
require_relative 'hello'

require 'minitest/autorun' # no need to require minitest

class TestHello < Minitest::Test
  def test_fails_without_end
    assert_equal say_hello, 'hello' # doesn't matter that the order is wrong
end
```

```
-:9: syntax error, unexpected end-of-input, expecting keyword_end
```

Even most text editors would help out with this simply by reindenting.

**Comment by droberts-ada** [comment] 2018-03-06 20:07
Thanks for the quick reply!

Sounds like the issue is that the missing `do...end` isn't the problem (in fact it's a supported feature). Rather, putting random test code in a describe block is the proximate cause of the error, and that's what Ruby is catching. Maybe there's a way to approach it where calling `must_whatever` outside of an `it` produces a more friendly error, but I'm sure there are other variations on this pattern (notably `describe` with no `do...end`) that this won't fix.

**Comment by droberts-ada** [comment] 2018-03-06 20:35
As far as pedagogy is concerned, you're probably right that the assertion-style syntax would be easier to learn. Our decision to use BDD and the spec-style syntax is much more about philosophy than mechanics. BDD matches well with how we want them to think about testing. If we choose to revisit this decision, ease of use will definitely be one of our criteria, but not the only one.

It's also true that we'll soon move into the Rails part of the curriculum, which is chock full of DSLs. It's valuable to get used to the idea of "Ruby that doesn't look like Ruby" before adding in all the context of a web server.

**Comment by droberts-ada** [comment] 2018-03-06 20:38
Could be the band-aid fix for us is to show them this error in advance, so they know what they're looking at. This is definitely a real usability issue with the framework, but it might not be one that it's possible / worthwhile to fix.

**Comment by zenspider** [comment] 2018-03-06 22:14
[deleted large response about Ada & pedagogy]

OK. 2 things:

1. I still think using minitest/spec for teaching is a _Big Mistake™_, esp. this early.
2. I totally overlooked this... You're using deprecated forms. This will blow up **_soon_**. `value.must_equal expected` needs to be written: `X(value).must_equal expected` where `X` can be `_`, `value`, or `expect`. See:

http://docs.seattlerb.org/minitest/Minitest/Spec/DSL/InstanceMethods.html#method-i-_

for more info.

2. (b) using this form changes the error from:

```
<blahblah>/minitest/spec.rb:23:in `must_equal': undefined method `assert_equal' for nil:NilClass (NoMethodError)
```

to:

```
bug749.rb:11:in `block in <main>': undefined method `_' for #<Class:0x00007f936809b3e0> (NoMethodError)
```

this points to the line causing the problem and feel more direct/clear to me.

**Comment by zenspider** [comment] 2018-03-06 23:36
Assuming my github sync cronjob is still running correctly on the new server... I just pushed a fix for this. I *also* pushed deprecation warnings for using global expectation methods. This will probably be my last release before MT6 that will obliterate those methods.

**Closed by zenspider** 2018-03-06 23:36 UTC

**Comment by droberts-ada** [comment] 2018-03-07 22:30
Thanks for the help, and also thanks for the warning!
